project:
  type: book

book:
  title: "Hyperparameter Tuning Techniques"
  author: "Mariano Villafuerte"
  chapters:
    - index.qmd
    - 01_introduction.qmd
    - 02_eda.qmd
    - 03_grid_search.qmd
    - 04_random_search.qmd
    - 05_bayesian_optim.qmd
    - references.qmd

bibliography: references.bib

format: 
  html:
    toc: TRUE
    embed-resources: TRUE
    theme: flatly
    lang: en
    font-size: 1.1em
    include-in-header: 
    - text: |
        <style>
          body { 
            line-height: 2;
          }
        </style>

editor: visual

